### ISSUE TITLE
Make shared default admin demo user for GraphKB/IPR

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_docs#57]
To simplify the setup it would be great to add the same admin user for both IPR and GraphKB. This will require the following tasks

- [x] @mathieulemieux  to change the default "graphkb_admin" user in the graphkb api repo to be "pori_admin"
- [x] @brayden-bcgsc  to add a new "pori_admin" user to the IPR default db dump with admin access to IPR
- [x] @mathieulemieux or @brayden-bcgsc  to rename the user "graphkb_admin" in the keycloak dump json to pori_admin and update the accompanying docs

**Comment by creisle** [comment]
@brayden-bcgsc and @mathieulemieux when the tasks above are done can you post the applicable release version of the API container back here

**Comment by mathieulemieux** [comment]
In order to test [these changes](https://github.com/bcgsc/pori/issues/57#issue-1239215682), I did the following on dockerdev server:
- strop and remove all pori containers
- clone a new copy of **pori**, **pori_ipr_api** and **pori_grapgkb_api** repos
- in **pori_ipr_api**:
  - checkout **develop** branch (includes [changes](https://github.com/bcgsc/pori_ipr_api/compare/32aeb66f2b97e856d25a7d5d567ba305e5ebae09...042d6bdf6c52a6b72f545e320b315849d32bf320) to demo/ipr_demodb.postgres.dump)
- in **pori_graphkb_api**:
  - checkout **feature/KBDEV-977-make-shared-default-admin-demo-user-for-graphkb-ipr-57** branch (includes [changes](https://github.com/bcgsc/pori_graphkb_api/compare/feature/KBDEV-977-make-shared-default-admin-demo-user-for-graphkb-ipr-57) to src/repo/schema.js)
- in **pori**:
  - checkout **feature/make-shared-default-admin-demo-user-for-graphkb-ipr-57** branch (includes [changes](https://github.com/bcgsc/pori/compare/develop...feature/make-shared-default-admin-demo-user-for-graphkb-ipr-57) to demo/kc_realmexport.json)
  - made [these changes](https://github.com/bcgsc/pori/compare/feature/make-shared-default-admin-demo-user-for-graphkb-ipr-57...test/docker-compose-with-local-apis-build) to docker-compose.dev.yml
  - mkdir -p databases/{postgres,orientdb}/{backup,data} && mkdir keys
  - docker-compose -f docker-compose.dev.yml up -d --build
  - exported 3000, 5000, 8080, 8081 & 8888.

Here are the Keycloak users:
![image](https://user-images.githubusercontent.com/4022327/171482994-62115ca8-f293-4745-90d5-45754af635f7.png)

Here are the GraphKb users:
![image](https://user-images.githubusercontent.com/4022327/171682547-7b59ce2d-93d0-4eac-bfa1-4c44fe777557.png)

Errors I got:
- I can't log into IPR using pori_admin; only iprdemo will work
- Going from IPR to GraphKB while logged to IPR with iprdemo isn't possible without relogging with pori_admin user

**Comment by mathieulemieux** [comment]
Ok, in order to make it work, we need to update the ipr_demodb image too.
It's look like this: before starting the containers with docker-compose,
- in **pori_ipr_api** repo, run the following command: "docker build -f Dockerfile.db -t bcgsc/pori-ipr-demodb:pori_admin ." (Ty @brayden-bcgsc !)
- in **pori** repo, make an additional change to the docker-compose.dev.yml to make the ipr_db container based on image bcgsc/pori-ipr-demodb:pori_admin instead of bcgsc/pori-ipr-demodb:latest

Everything went well.
The pori_admin user allows to switch from IPR to GraphKB without the need to logout.

**Comment by mathieulemieux** [comment]
On pori_graphkb_api, replace feature/KBDEV-977-make-shared-default-admin-demo-user-for-graphkb-ipr-57 from develop by bugfix/KBDEV-977-make-shared-default-admin-demo-user-for-graphkb-ipr-57 from master. Commit the same changes as before and re-tested everything on dockerdev. Ready to PR.

**Comment by mathieulemieux** [comment]
For info, here is the previous PR for default db dump made by @RaphaelPletz to pori_ipr_api: https://github.com/bcgsc/pori_ipr_api/pull/160.

**Comment by mathieulemieux** [comment]
Here are the different users in ipr, graphkb and keycloak:
![image](https://user-images.githubusercontent.com/4022327/173438367-0ff00eae-6d2e-4078-abbd-6acb94b962b3.png)
Should we get rid of colab_demo and iprdemo?

**Comment by creisle** [comment]
> Here are the different users in ipr, graphkb and keycloak: ![image](https://user-images.githubusercontent.com/4022327/173438367-0ff00eae-6d2e-4078-abbd-6acb94b962b3.png) Should we get rid of colab_demo and iprdemo?

we should only remove the users that were replaced with the new account (pori_admin) or that are no longer created

- colab_demo should still be being created, it is used for the colab/jupyter notebooks in the docs
- please double check that iprdemo still exists in IPR, if it does it can be left as well

**Comment by mathieulemieux** [comment]
Looks like we are still using the iprdemo user in IPR so I'll let it there: https://github.com/bcgsc/pori_ipr_api/blob/b5038f806e183f0432a25078ed682b68ad9081f6/demo/clean_db_for_demo.js#L167-L206

**Comment by mathieulemieux** [comment]
https://github.com/bcgsc/pori/pull/59

**Comment by mathieulemieux** [comment]
Closed by PR https://github.com/bcgsc/pori/pull/59
